### ISSUE TITLE
Error Entering VS Code from WSL

### ISSUE THREAD

**Issue by vgorgen** [ucoruh/asn1c-wsl-sample#3]
When I write "code ." command line it enter vs code but not from wsl
Solution is remote development. you should download this extension.
![remote_development](https://user-images.githubusercontent.com/92218276/193848713-151bb303-a613-4bde-bb7d-9ea8430cab3a.PNG)

**Comment by ucoruh** [comment]
"Open VsCode in WSL" updated missing extensions are added for recommendation to install before running vs code.
