### ISSUE TITLE
Error "C:\Program Files\mingw-w64\bin\gcc.exe: command not found" 

### ISSUE THREAD

**Issue by vgorgen** [ucoruh/asn1c-wsl-sample#4]
**_**When I wrote this command line**_** 
![gcc_command](https://user-images.githubusercontent.com/92218276/194344118-ea8a62e7-71c5-4cd9-bda5-698b63d2eace.PNG)

**_it gives me an error like that_** 
![Capture](https://user-images.githubusercontent.com/92218276/194344980-a2979ac3-b3d0-4896-b30b-95d09d712394.PNG)

What can I do?

**Comment by ucoruh** [comment]
Because commad-line in WSL so it will use GCC in WSL, not windows. Try GCC
