### ISSUE TITLE
Autoreconf -iv Error

### ISSUE THREAD

**Issue by vgorgen** [ucoruh/asn1c-wsl-sample#5]
When I wrote "**autoreconf -iv**" command line it give like this error

![Capture](https://user-images.githubusercontent.com/92218276/194782223-bb3851f7-98c3-4bc4-ac5d-0ba534bd3772.PNG)

Solution: 
I solved this problem by installing "autoconf" package
`sudo apt-get install autoconf`

**Comment by ucoruh** [comment]
Solved in this commit 

https://github.com/ucoruh/asn1c-wsl-sample/commit/4341aaa803be2596fa88c57b240861f24ddfb00c
